/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kata.marsrover;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class MarsRoverTest {

	@Test void testRoverCreation() {
    	assertEquals("Rover", new Object());
    }
}
